version: "2.1"

services:
     elasticsearch:
          image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
          container_name: elasticsearch
          hostname: elasticsearch
          volumes:
               - elasticsearch:/usr/share/elasticsearch/data
          environment:
               ES_JAVA_OPTS: "-Xmx256m -Xms256m"
               ELASTIC_PASSWORD: "root"
               xpack.security.enabled: "true"
               xpack.monitoring.collection.enabled: "true"
               discovery.type: "single-node"
          healthcheck:
               test: ["CMD", "curl", "-f", "http://elastic:root@elasticsearch:9200"]
          networks:
               - elastic

     app:
          image: cvindexer_api:0.1
          container_name: app
          restart: on-failure
          environment:
               ENV_PROFILE: "prod"
               ELASTIC_ENDPOINT: "elasticsearch:9200"
          healthcheck:
               test: ["CMD", "curl", "-f", "http://app:8080/api/v1/cv?keyword=java"]
          
          depends_on:
               elasticsearch:
                    condition: service_healthy
               logstash:
                    condition: service_healthy
          
          networks:
               - elastic
               - publicnetwork
               -
networks:
     elastic:
          driver: bridge
     publicnetwork:
          driver: bridge

volumes:
     elasticsearch:
          driver: local
