version: "2.1"

services:
     elasticsearch:
          image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
          container_name: elasticsearch
          hostname: elasticsearch
#          volumes:
#               - ./data/elasticsearch:/usr/share/elasticsearch/data
          environment:
               ES_JAVA_OPTS: "-Xmx256m -Xms256m"
               ELASTIC_PASSWORD: "root"
               xpack.security.enabled: "true"
               xpack.monitoring.collection.enabled: "true"
               discovery.type: "single-node"
          healthcheck:
               test: ["CMD", "curl", "-f", "http://elastic:root@elasticsearch:9200"]
          networks:
               - elastic
     app:
          container_name: app
          build: .
          restart: on-failure
          ports:
               - "8080:8080"
          environment:
               ENV_PROFILE: "prod"
               ELASTIC_ENDPOINT: "elasticsearch:9200"
          volumes:
               - ./data/cv:/root/.m2
          healthcheck:
               test: ["CMD", "curl", "-f", "http://app:8080/api/v1/cv?keyword=java"]
          depends_on:
               elasticsearch:
                    condition: service_healthy
               logstash:
                    condition: service_healthy
          networks:
               - elastic

networks:
     elastic:
          driver: bridge
